### ISSUE TITLE
Read information about projects from configuration file

### ISSUE THREAD

**Issue by sergey-ostapenko** [mbtproject/mbt#86]
## Suggestion 
Add possibility to cache list of paths to project configurations to make `mbt` work faster.

On big a repository operation to find all .mbt.yml files can take really long time.
Because of that we have quite long wait time for scenarios when user want to perform operation for the whole repository. For example:
``` mbt describe local --all ```
of just
``` mbt build local --name MyProject ```

For such cases it will be useful to support `non-interactive` scenario of work, when we can:
1. Perform cache operation on mbt to find all projects in repository and store it to configuration file that can be source controled or used locally:
``` mbt cache-projects local ```
2. Run mbt in non-interactive mode that will use configuration file to gather information about projects in the repository.

**Comment by buddyspike** [comment]
This is largely due to blind workspace traversal we do to detect modules in locally. It traverses the entire directory tree without respecting `.gitignore`. As a result, if you run `local` commands on repository with say... `node_modules`, it might take up a few seconds.

Having said that, we revised this implementation recently to address a different issue and in the process I realised that we should be able to discover modules without traversing the file system quite efficiently. It requires changing the below routine to perform two tasks:

- Discover modules in head
- Discover modules in workspace (same as what you get when you run `mbt describe local`
And union the two sets.
- Finally get rid of `ModulesInWorkspace` function in `discover.go`

https://github.com/mbtproject/mbt/blob/master/lib/manifest_builder.go#L134


It will be much faster.

**Comment by sergey-ostapenko** [comment]
> . As a result, if you run local commands on repository with say... node_modules, it might take up a few seconds

Exactly our situation, but we have a lot of `node_modules` folders. So it would be great to have these improvements to allow use this tool more efficiently.
