### ISSUE TITLE
[bug] mbt always return exit code 0

### ISSUE THREAD

**Issue by tuannvm** [mbtproject/mbt#99]
**Which mbt command are you having troubles with?**

- run-in

**What's the current behaviour?**
- Currently mbt doesn't retain cmd's exit code & always return `exit code 0`

**What's the expected behaviour?**
- Should return sub-command's exit code probably

**Environment**

- mbt version: 0.19.0
- os: linux
- arch: amd64

**Comment by buddyspike** [comment]
Thanks for reporting this. This is currently by design. But I see your problem and happy to fix this after we gather some more info.

- What do we do when command fails in one module? Currently, as you noted, we move on to executing the command in next available module. Should we continue to do this or should we fail fast? Or have an option to control this (`--fail-fast`)

- What should be the return code if a command fails? If we are operating under a option like `fail-fast`, we can certainly return the exit code from the user command. However, if we are moving on, and there are multiple failures, we need a strategy to decide which exit code to return.

My preference is to have `--fail-fast` option. And if we run commands without this option, we can simply return `1` (For example, this is what build command does at the moment).

**Comment by tuannvm** [comment]
Thanks for the prompt answer! Yea they `--fail-fast` option would be definitely helpful.
And keeping return `1` which similar to build command which is better than return `0` even though at least one module failed
